# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 289e5fa170c85b14ce9d3e6ff8413c70f2bf60190a902a268f2ca4a22f403926746daecdea9b203fba5082d813a1982b9c0a491da5853b106a75b1cd53c960e6

test:
  secret_key_base: 7ba64be5b85c9c254ef3f1cdc71f9916009228312b0d9f335dfc862aa392ce7124cb643884b3d6b00d0ee288d34832825b49139c937f283721a5df07fa4a9085

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
